### ISSUE TITLE
Can you provide a detail readme to start the project? 

### ISSUE THREAD

**Issue by yanxp** [yuhuayc/da-faster-rcnn#1]
For example,the related datasets and how to test their performance? Thanks!

**Comment by yuhuayc** [comment]
I will provide an example how to prepare dataset soon. To test the performance, use the script in ./tools/test_net.py

**Comment by yanxp** [comment]
no response ？？

**Comment by lly2111101** [comment]
@yanxp 
hi, have you try to explore the usage of this code? I mean that do you run the code with unlabeled target domain data set successfully?

**Comment by yanxp** [comment]
Not yet.

**Comment by yuhuayc** [comment]
Hi guys, very sorry for the late reply. An example is provided in prepare_data/prepare_data.m
