### ISSUE TITLE
How to download foggy image set?

### ISSUE THREAD

**Issue by xychen9459** [yuhuayc/da-faster-rcnn#10]
Hi. I'm trying to download cityscape dataset for training. I cannot download `leftImg8bit_trainvaltest_foggy` unless I send a request. However, I couldn't find contact information to send requests. 

How could I send request to download the foggy dataset?  Thx.

**Comment by yuhuayc** [comment]
You can contact the Cityscapes team for accessing the dataset. Their email: mail@cityscapes-dataset.net

**Comment by kabrau** [comment]
Hi @xychen9459 and @yuhuayc 
I sent email to mail@cityscapes-dataset.net, but I did not receive an answer.
Do you have other contact ?
Best regards
Marcelo

> Hi
> 
> I'm a Ph.D. student from Brazil and my research is domain adaptation for helping blind people.
> I would like to use Cityscape and Foggy Cityscape to validation my research.
> Can you give me access to download leftImg8bit_trainvaltest_foggy.zip  ?
> 
> Best regards,
> 
> Marcelo Cabral Ghilardi
> Ph.D. student  
> DaVint - Data Visualization and Interaction Lab
> School of Technology, PUCRS-Pontifical Catholic University of Rio Grande do Sul
> Porto Alegre, Brazil
