### ISSUE TITLE
I can't download left8Img_trainvaltest_foggy.zip

### ISSUE THREAD

**Issue by HalfMooon** [yuhuayc/da-faster-rcnn#13]
I use my student mail to creat a count. But I find I can not download the foggy dataset. I only can download  Transmittance.zip

**Comment by zqdeepbluesky** [comment]
me too

**Comment by ksaito-ut** [comment]
Three weeks ago, I sent a request to publicize the dataset and I could download it.

**Comment by yuhuayc** [comment]
Hi guys, could you please contact the Cityscapes team to apply the access to the foggy data? I don't have the permission to distribute the data, sorry!

**Comment by zhangwenwen** [comment]
There are three different versions of Foggy Cityscapes for the 5000 training+validation+testing Cityscapes images, each characterized by a constant attenuation coefficient which determines the fog density and the visibility range. The values of the attenuation coefficient are 0.005, 0.01 and 0.02m-1 and correspond to visibility ranges of 600, 300 and 150m respectively. Which version is used in this paper?

**Comment by yuhuayc** [comment]
Hi Wenwen,

I was using the version '0.02',

you could use this script to process the data.
https://github.com/yuhuayc/da-faster-rcnn/blob/master/prepare_data/prepare_data.m
