### ISSUE TITLE
problem about prepare_data.m

### ISSUE THREAD

**Issue by codingwolfman** [yuhuayc/da-faster-rcnn#19]
>> system(sprintf('find %s -name "*.png"', ...
    fullfile(source_data_dir,'leftImg8bit','train')))
拒绝访问 - CITYSCAPES\LEFTIMG8BIT\TRAIN 
找不到文件 - -NAME 

ans =

     1

**Comment by andrewXiaoyu** [comment]
Hi, how are you! I have the same problem as you. How Do You Solve It? I ran the script as an administrator
