### ISSUE TITLE
Is the consistency regularization exists in train.prototxt?

### ISSUE THREAD

**Issue by FlyingQianMM** [yuhuayc/da-faster-rcnn#4]
It seems that the train.prototxt file does not contain the the consistency regularization in your paper. 
Is there something I overlook? If not, could you supply a full file? Thanks a lot!

**Comment by wjx2** [comment]
@FlyingQianMM 
hi, do you get the full file?

**Comment by lly2111101** [comment]
@FlyingQianMM 
hi, do you run the codes with unlabeled target domain data set successfully?

**Comment by tingjiaqi123** [comment]
@lly2111101 
hi, do you run the codes with unlabeled target domain data set successfully so far?

**Comment by yuhuayc** [comment]
Hi guys, please use the caffe2 implementation if you want to use consistency loss: https://github.com/krumo/Detectron-DA-Faster-RCNN

**Comment by Liyw979** [comment]
Yes!This is bothering me too
